// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByXoUG5cMKsVVm74HvTLPIwyw-iXhdob8',
    appId: '1:287741351758:web:f9fdbbbbf7e2f01457301f',
    messagingSenderId: '287741351758',
    projectId: 'codex-cd913',
    authDomain: 'codex-cd913.firebaseapp.com',
    storageBucket: 'codex-cd913.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7kgFGNkiZXCqqBfgJ5-oTSCXFdgbjJzo',
    appId: '1:287741351758:android:4a0efb0df98da27b57301f',
    messagingSenderId: '287741351758',
    projectId: 'codex-cd913',
    storageBucket: 'codex-cd913.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfs6U_qvEJakK_uD4OP1ztQifC1y5KSZE',
    appId: '1:287741351758:ios:17de9981de77211b57301f',
    messagingSenderId: '287741351758',
    projectId: 'codex-cd913',
    storageBucket: 'codex-cd913.appspot.com',
    iosClientId: '287741351758-vvvseuchrjca8h15rkg0fjlq6kj41nhq.apps.googleusercontent.com',
    iosBundleId: 'com.example.codex',
  );
}
